config/routes.rb
# frozen_string_literal: true

class PageUrlConstrainer
  def matches?(request)
    name = request.path.delete("/")
    Page.find_by_name(name)
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root "dashboard#index"
    resources :pages, :alerts, :sliders, :collapsibles, :markers, :card_groups,
              :contact_emails, :exhibits, :testimonials, :collections
    resources :photo_albums do
      resource :photos, only: %i[new create]
    end
    resources :settings, only: %i[show edit update]
    resources :users, only: %i[index destroy update]
  end

  namespace :docs do
    root "home#index"
    get "alerts", to: "how_to_use#alerts"
    get "card_groups", to: "how_to_use#card_groups"
    get "collapsibles", to: "how_to_use#collapsibles"
    get "collections", to: "how_to_use#collections"
    get "contacts", to: "how_to_use#contacts"
    get "exhibits", to: "how_to_use#exhibits"
    get "markers_maps", to: "how_to_use#markers_maps"
    get "pages", to: "how_to_use#pages"
    get "photo_albums", to: "how_to_use#photo_albums"
    get "settings", to: "how_to_use#settings"
    get "sliders", to: "how_to_use#sliders"
    get "testimonials", to: "how_to_use#testimonials"
    get "make_admin", to: "how_to_use#make_admin"
  end

  devise_for :users
  root "home#index"
  post "pages/create_message", as: "create_message"
  resources :photo_albums, only: :show
  resources :testimonials, only: %i[new create]
  constraints(PageUrlConstrainer.new) do
    get ":name" => "pages#show"
  end

  # Error Handling
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#change_request_error", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/exhibit.rb
# frozen_string_literal: true

class Exhibit < ApplicationRecord
  validates :title, :icon, :description, :order, :page_id, presence: true

  belongs_to :page

  scope :is_active, -> { where(active: true).order(:order) }

  def page_name
    return if page_id.blank?
    page.title
  end
end

app/controllers/admin/exhibits_controller.rb
# frozen_string_literal: true

module Admin
  class ExhibitsController < AdminController
    before_action :set_exhibit, except: %i[index new create]

    def index
      @q = Exhibit.search(params[:q])
      @exhibits = @q.result.page(params[:page])
    end

    def new
      @exhibit = Exhibit.new
    end

    def show; end

    def create
      @exhibit = Exhibit.new(exhibit_params)

      if @exhibit.save
        redirect_to admin_exhibits_path,
                    notice: "Exhibit Created Successfully!"
      else
        render :new
      end
    end

    def edit; end

    def update
      if @exhibit.update(exhibit_params)
        redirect_to admin_exhibits_path,
                    notice: "Exhibit Updated Successfully!"
      else
        render :edit
      end
    end

    def destroy
      @exhibit.destroy
      redirect_to admin_exhibits_path,
                  notice: "Exhibit Deleted Successfully!"
    end

    private

    def set_exhibit
      @exhibit = Exhibit.find(params[:id])
    end

    def exhibit_params
      params.require(:exhibit).permit(
        :page_id, :title, :description, :order, :active, :icon
      )
    end
  end
end

app/views/admin/exhibits/_form.html.haml
.row.main-form
  = simple_form_for [:admin, exhibit], html: { class: "col s12" } do |f|
    .col.s12
      - unless exhibit.errors.empty?
        .form-errors.red.lighten-1
          %ul
            - exhibit.errors.full_messages.each do |msg|
              %li= msg
    = f.input :title, maxlength: "75", icon: "title",
      wrapper_html: { class: "m6 s12" }
    = f.input :icon, icon: "fingerprint", wrapper_html: { class: "m6 s12" }
    = f.input :description, wrapper_html: { class: "s12" }, as: :text
    = f.input :page_id, collection: Page.pages_tabs.map{ |p| [p.title, p.id] },
      prompt: "Select a Page", wrapper_html: { class: "m6 s12" }
    = f.input :order, icon: "format_list_numbered",
      wrapper_html: { class: "m6 s12" }
    = f.input :active, wrapper_html: { class: "s12" }
    = f.button :submit, class: "right"

app/views/admin/exhibits/edit.html.haml
- content_for :page_title do
  Edit Exhibit

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", exhibit: @exhibit

= helper_fab(docs_exhibits_path)

app/views/admin/exhibits/index.html.haml
- content_for :page_title do
  Exhibits

- content_for :page_button do
  = link_to new_admin_exhibit_path,
    class: "btn-floating btn-large halfway-fab waves-effect waves-light" do
    = material_icon.add

.page-wrapper
  .row
    .col.s12
      .card-panel
        .row
          .col.s12
            .right= page_entries_info @exhibits, entry_name: "Exhibit"
        %table.bordered.highlight.table.responsive-table
          %thead
            %th{ scope: "col", data: { field: "Title" } }
              = sort_link @q, :title
            %th{ scope: "col", data: { field: "Icon" } }
              = sort_link @q, :icon
            %th{ scope: "col", data: { field: "Page Name" } }
              = sort_link @q, :page_id
            %th{ scope: "col", data: { field: "Order" } }
              = sort_link @q, :order
            %th{ scope: "col", data: { field: "Active" } }
              = sort_link @q, :active
            %th{ scope: "col", colspan: "2" }
          %tbody
            - @exhibits.each do |exhibit|
              %tr.table__row{ role: "link", tabindex: "0",
                data: { url: admin_exhibit_path(exhibit) } }
                %td
                  .truncate= exhibit.title
                %td= exhibit.icon
                %td= exhibit.page_name
                %td= exhibit.order
                %td
                  - if exhibit.active?
                    = material_icon.check_box
                  - else
                    = material_icon.check_box_outline_blank
                %td
                  = link_to "Edit", edit_admin_exhibit_path(exhibit),
                    class: "action-edit"
                %td
                  = link_to "Delete", admin_exhibit_path(exhibit),
                    class: "action-destroy red-text", rel: "nofollow",
                    data: { method: :delete, confirm: "Are You Sure?" }
        .center.section
          = paginate @exhibits

= helper_fab(docs_exhibits_path)

app/views/admin/exhibits/new.html.haml
- content_for :page_title do
  New Exhibit

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", exhibit: @exhibit

= helper_fab(docs_exhibits_path)

app/views/admin/exhibits/show.html.haml
- content_for :page_title do
  Exhibit

.row
  .col.s12.offset-m1.m10
    .card-panel.main-view
      .row
        .col.s12.m6.grid
          %span.label Title:
          = @exhibit.title
        .col.s12.m6.grid
          %span.label Icon:
          = @exhibit.icon
        .col.s12.m6.grid
          %span.label Page Name:
          = @exhibit.page_name
        .col.s12.m6.grid
          %span.label Order:
          = @exhibit.order
        .col.s12.m6
          %span.label Active:
          %span.icon
            - if @exhibit.active?
              = material_icon.check_box
            - else
              = material_icon.check_box_outline_blank
      .row
        .col.s12
          %span.label Description:
          = @exhibit.description

.fixed-action-btn.click-to-toggle.toolbar
  %a.btn-floating.btn-large.waves-effect.waves-light
    = material_icon.menu
  %ul
    %li.waves-effect.waves-light
      = link_to admin_exhibit_path(@exhibit), class: "red" do
        = material_icon.delete_forever
    %li.waves-effect.waves-light
      = link_to edit_admin_exhibit_path(@exhibit), class: "green" do
        = material_icon.edit