config/routes.rb
# frozen_string_literal: true

class PageUrlConstrainer
  def matches?(request)
    name = request.path.delete("/")
    Page.find_by_name(name)
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root "dashboard#index"
    resources :pages, :alerts, :sliders, :collapsibles, :markers, :card_groups,
              :contact_emails, :exhibits, :testimonials, :collections
    resources :photo_albums do
      resource :photos, only: %i[new create]
    end
    resources :settings, only: %i[show edit update]
    resources :users, only: %i[index destroy update]
  end

  namespace :docs do
    root "home#index"
    get "alerts", to: "how_to_use#alerts"
    get "card_groups", to: "how_to_use#card_groups"
    get "collapsibles", to: "how_to_use#collapsibles"
    get "collections", to: "how_to_use#collections"
    get "contacts", to: "how_to_use#contacts"
    get "exhibits", to: "how_to_use#exhibits"
    get "markers_maps", to: "how_to_use#markers_maps"
    get "pages", to: "how_to_use#pages"
    get "photo_albums", to: "how_to_use#photo_albums"
    get "settings", to: "how_to_use#settings"
    get "sliders", to: "how_to_use#sliders"
    get "testimonials", to: "how_to_use#testimonials"
    get "make_admin", to: "how_to_use#make_admin"
  end

  devise_for :users
  root "home#index"
  post "pages/create_message", as: "create_message"
  resources :photo_albums, only: :show
  resources :testimonials, only: %i[new create]
  constraints(PageUrlConstrainer.new) do
    get ":name" => "pages#show"
  end

  # Error Handling
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#change_request_error", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/collapsible.rb
# frozen_string_literal: true

class Collapsible < ApplicationRecord
  validates :name, :collapse_style, :usage_type, :order, presence: true

  belongs_to :page
  has_many :collapsible_items, inverse_of: :collapsible

  accepts_nested_attributes_for :collapsible_items, reject_if: :all_blank,
                                                    allow_destroy: true

  scope :usage_filtered, lambda { |usage|
    where("usage_type = ? AND active = ?", usage, true).order(:order)
  }

  scope :is_active, -> { where(active: true).order(:order) }
end

app/controllers/admin/collapsibles_controller.rb
# frozen_string_literal: true

module Admin
  class CollapsiblesController < AdminController
    before_action :set_collapsible, except: %i[index new create]

    def index
      @q = Collapsible.search(params[:q])
      @collapsibles = @q.result.page(params[:page])
    end

    def new
      @collapsible = Collapsible.new
    end

    def show; end

    def create
      @collapsible = Collapsible.new(collapsible_params)

      if @collapsible.save
        redirect_to admin_collapsibles_path,
                    notice: "Collapsible Created Successfully!"
      else
        render :new
      end
    end

    def edit; end

    def update
      if @collapsible.update(collapsible_params)
        redirect_to admin_collapsibles_path,
                    notice: "Collapsible Updated Successfully!"
      else
        render :edit
      end
    end

    def destroy
      @collapsible.destroy
      redirect_to admin_collapsibles_path,
                  notice: "Collapsible Deleted Successfully!"
    end

    private

    def set_collapsible
      @collapsible = Collapsible.find(params[:id])
    end

    def collapsible_params
      params.require(:collapsible).permit(
        :name, :active, :is_popout, :collapse_style, :usage_type, :order,
        :page_id, collapsible_items_attributes: %i[
id title body active icon order collapsible_id _destroy
]
      )
    end
  end
end

app/helpers/collapsible_helper.rb
# frozen_string_literal: true

module CollapsibleHelper
  def class_def(is_popout)
    "collapsible" + (is_popout ? " popout" : "")
  end
end

app/views/admin/collapsibles/_collapsible_item_fields.html.haml
%li.nested-fields
  .collapsible-header
    #{f.object.title.blank? ? 'New Item' : f.object.title}
  .collapsible-body.row{ style: "padding: 20px 0;" }
    .col.s12
      = link_to_remove_association "<i class='material-icons'>delete</i>".html_safe, f, data: { confirm: "Are You Sure?" }, class: "waves-effect waves-light red-text right"
    = f.input :title, icon: "title", wrapper_html: { class: "m6 s12" }
    = f.input :icon, icon: "fingerprint", wrapper_html: { class: "m6 s12" }
    = f.input :order, icon: "format_list_numbered",
      wrapper_html: { class: "m6 s12" }
    = f.input :active, wrapper_html: { class: "m6 s12" }
    = f.input :body, as: :ckeditor, label: false, wrapper_html: { class: "s12" }

app/views/admin/collapsibles/_form.html.haml
.row.main-form
  = simple_form_for [:admin, collapsible], html: { class: "col s12" } do |f|
    .col.s12
      - unless collapsible.errors.empty?
        .form-errors.red.lighten-1
          %ul
            - collapsible.errors.full_messages.each do |msg|
              %li= msg
    = f.input :name, maxlength: "100", icon: "title",
      wrapper_html: { class: "s12" }
    = f.input :collapse_style, collection: %w(accordion expandable),
      prompt: "Select a Collapse Style", wrapper_html: { class: "m6 s12" }
    = f.input :usage_type, collection: %w(Home-Page Page/Tab),
      prompt: "Select a Usage Type", wrapper_html: { class: "m6 s12" }
    = f.input :page_id, collection: Page.pages_tabs.map{ |p| [p.title, p.id] },
      prompt: "Select a Page", wrapper_html: { class: "coll_hiding hide s12" }
    = f.input :order, icon: "format_list_numbered",
      wrapper_html: { class: "m6 s12" }
    = f.input :is_popout, wrapper_html: { class: "m6 s12" }
    = f.input :active, wrapper_html: { class: "s12" }
    .col.s12
      %ul.collapsible#collapsible{ data: { collapsible: "accordion" } }
        = f.simple_fields_for :collapsible_items do |ci|
          = render "collapsible_item_fields", f: ci
    .col.s12.center
      = link_to_add_association "Add Item", f, :collapsible_items,
        class: "btn waves-effect waves-light",
        data: { "association-insertion-node": "ul#collapsible",
        "association-insertion-method": "append" }
    = f.button :submit, class: "right"

app/views/admin/collapsibles/edit.html.haml
- content_for :page_title do
  Edit Collapsible

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", collapsible: @collapsible

= helper_fab(docs_collapsibles_path)

app/views/admin/collapsibles/index.html.haml
- content_for :page_title do
  Collapsible Groups

- content_for :page_button do
  = link_to new_admin_collapsible_path,
    class: "btn-floating btn-large halfway-fab waves-effect waves-light" do
    = material_icon.add

.page-wrapper
  .row
    .col.s12
      .card-panel
        .row
          .col.s12
            .right= page_entries_info @collapsibles, entry_name: "Collapsible"
        %table.bordered.highlight.table.responsive-table
          %thead
            %th{ scope: "col", data: { field: "Name" } }
              = sort_link @q, :name
            %th{ scope: "col", data: { field: "Collapsible Style" } }
              = sort_link @q, :collapse_style
            %th{ scope: "col", data: { field: "Usage Type" } }
              = sort_link @q, :usage_type
            %th{ scope: "col", data: { field: "Order" } }
              = sort_link @q, :order
            %th{ scope: "col", data: { field: "Is Popout" } }
              = sort_link @q, :is_popout
            %th{ scope: "col", data: { field: "Active" } }
              = sort_link @q, :active
            %th{ scope: "col", colspan: "2" }
          %tbody
            - @collapsibles.each do |collapsible|
              %tr.table__row{ role: "link", tabindex: "0",
                data: { url: admin_collapsible_path(collapsible) } }
                %td= collapsible.name
                %td= collapsible.collapse_style
                %td= collapsible.usage_type
                %td= collapsible.order
                %td
                  - if collapsible.is_popout?
                    = material_icon.check_box
                  - else
                    = material_icon.check_box_outline_blank
                %td
                  - if collapsible.active?
                    = material_icon.check_box
                  - else
                    = material_icon.check_box_outline_blank
                %td
                  = link_to "Edit", edit_admin_collapsible_path(collapsible),
                    class: "action-edit"
                %td
                  = link_to "Delete", admin_collapsible_path(collapsible),
                    class: "action-destroy red-text", rel: "nofollow",
                    data: { method: :delete, confirm: "Are You Sure?" }
        .center.section
          = paginate @collapsibles

= helper_fab(docs_collapsibles_path)

app/views/admin/collapsibles/new.html.haml
- content_for :page_title do
  New Collapsible

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", collapsible: @collapsible

= helper_fab(docs_collapsibles_path)

app/views/admin/collapsibles/show.html.haml
- content_for :page_title do
  Collapsible Group

.row
  .col.s12.offset-m1.m10
    .card-panel.main-view
      .row
        .col.s12.m6.grid
          %span.label Name:
          = @collapsible.name
        .col.s12.m6.grid
          %span.label Collapse Style:
          = @collapsible.collapse_style
        .col.s12.m6.grid
          %span.label Usage Type:
          = @collapsible.usage_type
        .col.s12.m6.grid
          %span.label Order:
          = @collapsible.order
        .col.s12.m6
          %span.label Is Popout:
          %span.icon
            - if @collapsible.is_popout?
              = material_icon.check_box
            - else
              = material_icon.check_box_outline_blank
        .col.s12.m6
          %span.label Active:
          %span.icon
            - if @collapsible.active?
              = material_icon.check_box
            - else
              = material_icon.check_box_outline_blank
      .row
        .col.s12
          %h5 Collapsible Items
          %table.bordered.highlight
            %thead
              %th Title
              %th Icon
              %th Order
              %th Active
            %tbody
              - @collapsible.collapsible_items.order(:order).each do |item|
                %tr
                  %td= item.title
                  %td= item.icon
                  %td= item.order
                  %td
                    - if item.active
                      = material_icon.check_box
                    - else
                      = material_icon.check_box_outline_blank

.fixed-action-btn.click-to-toggle.toolbar
  %a.btn-floating.btn-large.waves-effect.waves-light
    = material_icon.menu
  %ul
    %li.waves-effect.waves-light
      = link_to admin_collapsible_path(@collapsible), class: "red" do
        = material_icon.delete_forever
    %li.waves-effect.waves-light
      = link_to edit_admin_collapsible_path(@collapsible), class: "green" do
        = material_icon.edit