config/routes.rb
# frozen_string_literal: true

class PageUrlConstrainer
  def matches?(request)
    name = request.path.delete("/")
    Page.find_by_name(name)
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root "dashboard#index"
    resources :pages, :alerts, :sliders, :collapsibles, :markers, :card_groups,
              :contact_emails, :exhibits, :testimonials, :collections
    resources :photo_albums do
      resource :photos, only: %i[new create]
    end
    resources :settings, only: %i[show edit update]
    resources :users, only: %i[index destroy update]
  end

  namespace :docs do
    root "home#index"
    get "alerts", to: "how_to_use#alerts"
    get "card_groups", to: "how_to_use#card_groups"
    get "collapsibles", to: "how_to_use#collapsibles"
    get "collections", to: "how_to_use#collections"
    get "contacts", to: "how_to_use#contacts"
    get "exhibits", to: "how_to_use#exhibits"
    get "markers_maps", to: "how_to_use#markers_maps"
    get "pages", to: "how_to_use#pages"
    get "photo_albums", to: "how_to_use#photo_albums"
    get "settings", to: "how_to_use#settings"
    get "sliders", to: "how_to_use#sliders"
    get "testimonials", to: "how_to_use#testimonials"
    get "make_admin", to: "how_to_use#make_admin"
  end

  devise_for :users
  root "home#index"
  post "pages/create_message", as: "create_message"
  resources :photo_albums, only: :show
  resources :testimonials, only: %i[new create]
  constraints(PageUrlConstrainer.new) do
    get ":name" => "pages#show"
  end

  # Error Handling
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#change_request_error", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  validates :title, :order, :page_id, presence: true

  belongs_to :page

  scope :is_active, -> { where(active: true).order(:order) }

  def page_name
    return if page_id.blank?
    page.title
  end
end

app/controllers/admin/collections_controller.rb
# frozen_string_literal: true

module Admin
  class CollectionsController < AdminController
    before_action :set_collection, except: %i[index new create]

    def index
      @q = Collection.search(params[:q])
      @collections = @q.result.page(params[:page])
    end

    def new
      @collection = Collection.new
    end

    def show; end

    def create
      @collection = Collection.new(collection_params)

      if @collection.save
        redirect_to admin_collections_path,
                    notice: "Collection Created Successfully!"
      else
        render :new
      end
    end

    def edit; end

    def update
      if @collection.update(collection_params)
        redirect_to admin_collections_path,
                    notice: "Collection Updated Successfully!"
      else
        render :edit
      end
    end

    def destroy
      @collection.destroy
      redirect_to admin_collections_path,
                  notice: "Collection Deleted Successfully!"
    end

    private

    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(
        :title, :order, :icon, :link, :page_id, :active, :is_header
      )
    end
  end
end

app/views/admin/collections/_form.html.haml
.row.main-form
  = simple_form_for [:admin, collection], html: { class: "col s12" } do |f|
    .col.s12
      - unless collection.errors.empty?
        .form-errors.red.lighten-1
          %ul
            - collection.errors.full_messages.each do |msg|
              %li= msg
    = f.input :title, icon: "title", wrapper_html: { class: "s12" }
    = f.input :page_id, collection: Page.pages_tabs.map{ |p| [p.title, p.id] },
      prompt: "Select a Page", wrapper_html: { class: "m6 s12" }
    = f.input :order, icon: "format_list_numbered",
      wrapper_html: { class: "m6 s12" }
    = f.input :icon, icon: "fingerprint", wrapper_html: { class: "m6 s12" }
    = f.input :link, icon: "link", wrapper_html: { class: "m6 s12" }
    = f.input :is_header, wrapper_html: { class: "m6 s12" }
    = f.input :active, wrapper_html: { class: "m6 s12" }
    = f.button :submit, class: "right"

app/views/admin/collections/edit.html.haml
- content_for :page_title do
  Edit Collection

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", collection: @collection

= helper_fab(docs_collections_path)

app/views/admin/collections/index.html.haml
- content_for :page_title do
  Collections

- content_for :page_button do
  = link_to new_admin_collection_path,
    class: "btn-floating btn-large halfway-fab waves-effect waves-light" do
    = material_icon.add

.page-wrapper
  .row
    .col.s12
      .card-panel
        .row
          .col.s12
            .right= page_entries_info @collections, entry_name: "Collection"
        %table.bordered.highlight.table.responsive-table
          %thead
            %th{ scope: "col", data: { field: "Title" } }
              = sort_link @q, :title
            %th{ scope: "col", data: { field: "Page Name" } }
              = sort_link @q, :page_id
            %th{ scope: "col", data: { field: "Icon" } }
              = sort_link @q, :icon
            %th{ scope: "col", data: { field: "Order" } }
              = sort_link @q, :order
            %th{ scope: "col", data: { field: "Is Header" } }
              = sort_link @q, :is_header
            %th{ scope: "col", data: { field: "Active" } }
              = sort_link @q, :active
            %th{ scope: "col", colspan: "2" }
          %tbody
            - @collections.each do |collection|
              %tr.table__row{ role: "link", tabindex: "0",
                data: { url: admin_collection_path(collection) } }
                %td= collection.title
                %td= collection.page_name
                %td= collection.icon
                %td= collection.order
                %td
                  - if collection.is_header?
                    = material_icon.check_box
                  - else
                    = material_icon.check_box_outline_blank
                %td
                  - if collection.active?
                    = material_icon.check_box
                  - else
                    = material_icon.check_box_outline_blank
                %td
                  = link_to "Edit", edit_admin_collection_path(collection),
                    class: "action-edit"
                %td
                  = link_to "Delete", admin_collection_path(collection),
                    class: "action-destroy red-text", rel: "nofollow",
                    data: { method: :delete, confirm: "Are You Sure?" }
        .center.section
          = paginate @collections

= helper_fab(docs_collections_path)

app/views/admin/collections/new.html.haml
- content_for :page_title do
  New Collection

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", collection: @collection

= helper_fab(docs_collections_path)

app/views/admin/collections/show.html.haml
- content_for :page_title do
  Collection

.row
  .col.s12.offset-m1.m10
    .card-panel.main-view
      .row
        .col.s12.m6.grid
          %span.label Title:
          = @collection.title
        .col.s12.m6.grid
          %span.label Page Name:
          = @collection.page_name
        .col.s12.m6.grid
          %span.label Order:
          = @collection.order
        .col.s12.m6.grid
          %span.label Icon:
          = @collection.icon
        .col.s12.m6.grid
          %span.label Link:
          = @collection.link
        .col.s12.m6
          %span.label Is Header:
          %span.icon
            - if @collection.is_header?
              = material_icon.check_box
            - else
              = material_icon.check_box_outline_blank
        .col.s12.m6
          %span.label Active:
          %span.icon
            - if @collection.active?
              = material_icon.check_box
            - else
              = material_icon.check_box_outline_blank

.fixed-action-btn.click-to-toggle.toolbar
  %a.btn-floating.btn-large.waves-effect.waves-light
    = material_icon.menu
  %ul
    %li.waves-effect.waves-light
      = link_to admin_collection_path(@collection), class: "red" do
        = material_icon.delete_forever
    %li.waves-effect.waves-light
      = link_to edit_admin_collection_path(@collection), class: "green" do
        = material_icon.edit