config/routes.rb
# frozen_string_literal: true

class PageUrlConstrainer
  def matches?(request)
    name = request.path.delete("/")
    Page.find_by_name(name)
  end
end

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root "dashboard#index"
    resources :pages, :alerts, :sliders, :collapsibles, :markers, :card_groups,
              :contact_emails, :exhibits, :testimonials, :collections
    resources :photo_albums do
      resource :photos, only: %i[new create]
    end
    resources :settings, only: %i[show edit update]
    resources :users, only: %i[index destroy update]
  end

  namespace :docs do
    root "home#index"
    get "alerts", to: "how_to_use#alerts"
    get "card_groups", to: "how_to_use#card_groups"
    get "collapsibles", to: "how_to_use#collapsibles"
    get "collections", to: "how_to_use#collections"
    get "contacts", to: "how_to_use#contacts"
    get "exhibits", to: "how_to_use#exhibits"
    get "markers_maps", to: "how_to_use#markers_maps"
    get "pages", to: "how_to_use#pages"
    get "photo_albums", to: "how_to_use#photo_albums"
    get "settings", to: "how_to_use#settings"
    get "sliders", to: "how_to_use#sliders"
    get "testimonials", to: "how_to_use#testimonials"
    get "make_admin", to: "how_to_use#make_admin"
  end

  devise_for :users
  root "home#index"
  post "pages/create_message", as: "create_message"
  resources :photo_albums, only: :show
  resources :testimonials, only: %i[new create]
  constraints(PageUrlConstrainer.new) do
    get ":name" => "pages#show"
  end

  # Error Handling
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#change_request_error", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/alert.rb
# frozen_string_literal: true

class Alert < ApplicationRecord
  validates :title, :name, :start_date, :end_date, presence: true
  validates :name, uniqueness: true
  validate :start_date_before_end_date
  validates_format_of :name, with: /\A([a-z_]*)\z/i, message: '%{value} can
                             only contain lowercase letters and underscores'
  scope :active_alerts, lambda {
    where(
      "active = :status AND :todays_date BETWEEN start_date AND end_date",
      status: true, todays_date: Date.today
    )
  }

  scope :dashboard, lambda {
    where(
      "start_date > :today AND end_date > :today AND active = :status",
      today: Date.today, status: true
    )
  }

  def start_date_before_end_date
    return if end_date.nil? && start_date.nil?
    return unless end_date < start_date
    errors.add(:start_date, "- Start can not be greater than End Date")
  end

  def strd_start
    start_date.to_formatted_s(:standard)
  end

  def strd_end
    end_date.to_formatted_s(:standard)
  end
end

app/controllers/admin/alerts_controller.rb
# frozen_string_literal: true

module Admin
  class AlertsController < AdminController
    before_action :set_alert, except: %i[index new create]

    def index
      @q = Alert.search(params[:q])
      @alerts = @q.result.page(params[:page])
    end

    def new
      @alert = Alert.new
    end

    def show; end

    def create
      @alert = Alert.new(alert_params)

      if @alert.save
        redirect_to admin_alerts_path, notice: "Alert Created Successfully!"
      else
        render :new
      end
    end

    def edit; end

    def update
      if @alert.update(alert_params)
        redirect_to admin_alerts_path, notice: "Alert Updated Successfully!"
      else
        render :edit
      end
    end

    def destroy
      @alert.destroy
      redirect_to admin_alerts_path, notice: "Alert Deleted Successfully!"
    end

    private

    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(
        :name, :title, :content, :start_date, :end_date, :active
      )
    end
  end
end

app/views/admin/alerts/_form.html.haml
.row.main-form
  = simple_form_for [:admin, alert], html: { class: "col s12" } do |f|
    .col.s12
      - unless alert.errors.empty?
        .form-errors.red.lighten-1
          %ul
            - alert.errors.full_messages.each do |msg|
              %li= msg
    = f.input :title, maxlength: "75", icon: "title",
      wrapper_html: { class: "s12" }
    = f.input :name, maxlength: "25", icon: "subtitles",
      help_text: "Name can only have lowercase letters and underscores",
      wrapper_html: { class: "s12" }
    = f.input :start_date, icon: "event_available", as: :string,
      wrapper_html: { class: "m6 s12" },
      input_html: { class: "datepicker",
                    value: date_picker(f.object.start_date) }
    = f.input :end_date, icon: "event_busy", as: :string,
      wrapper_html: { class: "m6 s12" },
      input_html: { class: "datepicker",
                    value: date_picker(f.object.end_date) }
    = f.input :active, wrapper_html: { class: "s12" }
    .row
      .col.s12.ckeditor-input
        = f.cktext_area :content
    = f.button :submit, class: "right"

app/views/admin/alerts/edit.html.haml
- content_for :page_title do
  Edit Alert

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", alert: @alert

= helper_fab(docs_alerts_path)

app/views/admin/alerts/index.html.haml
- content_for :page_title do
  Alerts

- content_for :page_button do
  = link_to new_admin_alert_path,
    class: "btn-floating btn-large halfway-fab waves-effect waves-light" do
    = material_icon.add

.page-wrapper
  .row
    .col.s12
      .card-panel
        .row
          .col.s12
            .right= page_entries_info @alerts, entry_name: "Alert"
        %table.bordered.highlight.table.responsive-table
          %thead
            %th{ scope: "col", data: { field: "Title" } }
              = sort_link @q, :title
            %th{ scope: "col", data: { field: "Name" } }
              = sort_link @q, :name
            %th{ scope: "col", data: { field: "Start Date" } }
              = sort_link @q, :start_date
            %th{ scope: "col", data: { field: "End Date" } }
              = sort_link @q, :end_date
            %th{ scope: "col", data: { field: "Active" } }
              = sort_link @q, :active
            %th{ scope: "col", colspan: "2" }
          %tbody
            - @alerts.each do |alert|
              %tr.table__row{ role: "link", tabindex: "0",
                data: { url: admin_alert_path(alert) } }
                %td
                  .truncate= alert.title
                %td= alert.name
                %td= alert.strd_start
                %td= alert.strd_end
                %td
                  - if alert.active?
                    = material_icon.check_box
                  - else
                    = material_icon.check_box_outline_blank
                %td
                  = link_to "Edit", edit_admin_alert_path(alert),
                    class: "action-edit"
                %td
                  = link_to "Delete", admin_alert_path(alert),
                    class: "action-destroy red-text", rel: "nofollow",
                    data: { method: :delete, confirm: "Are You Sure?" }
        .center.section
          = paginate @alerts

= helper_fab(docs_alerts_path)

app/views/admin/alerts/new.html.haml
- content_for :page_title do
  New Alert

.row
  .col.s12.offset-m1.m10
    .card-panel
      = render "form", alert: @alert

= helper_fab(docs_alerts_path)

app/views/admin/alerts/show.html.haml
- content_for :page_title do
  Alert

.row
  .col.s12.offset-m1.m10
    .card-panel.main-view
      .row
        .col.s12.m6.grid
          %span.label Title:
          = @alert.title
        .col.s12.m6.grid
          %span.label Name:
          = @alert.name
        .col.s12.m6.grid
          %span.label Start Date:
          = @alert.strd_start
        .col.s12.m6.grid
          %span.label End Date:
          = @alert.strd_end
        .col.s12.m6
          %span.label Active:
          %span.icon
            - if @alert.active?
              = material_icon.check_box
            - else
              = material_icon.check_box_outline_blank
      .row
        .col.s12
          %span.label Content:
          = @alert.content.html_safe

.fixed-action-btn.click-to-toggle.toolbar
  %a.btn-floating.btn-large.waves-effect.waves-light
    = material_icon.menu
  %ul
    %li.waves-effect.waves-light
      = link_to admin_alert_path(@alert), class: "red" do
        = material_icon.delete_forever
    %li.waves-effect.waves-light
      = link_to edit_admin_alert_path(@alert), class: "green" do
        = material_icon.edit